[package]
name = "coprelos"
version = "0.1.0"
edition = "2021"

[dependencies]
openff-toolkit = { path = "openff-toolkit" }

[workspace]
members = [ "openff-interchange","openff-toolkit", "openff-units", "openmm"]
resolver = "2"
